### PR TITLE
Fixed results for floating point input

### PR DESCRIPTION
**Pull request by yashu-seth**
in OhmsLaw and OhmsLaw_AC.
Removed expressions giving incorrect results in floating point inputs.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
I think we need an update with 

``` py
from __future__ import division
```

on top of the file.

**Comment by yashu-seth** [comment]
Should I undo the previous changes and add 
 " from __ future __ import division "
or simply add the line on top keeping the previous changes?

**Comment by yashu-seth** [comment]
Hello,
Can you please tell me if BinPy would be participating in GSoC 2016 or not.
I have also sent you a reply on your response on my last commit. Kindly see
it.
Thanks.
Yashu Seth

**Comment by OrkoHunter** [comment]
I don't know if there is any need of `float()` function. The divisions only and `from __ future __ import division` in the top will do the job.

@debugger22

**Comment by yashu-seth** [comment]
Yes I think there is no need of float function . I'll add the <code> from __ future __ import division </code> on top.

**Comment by yashu-seth** [comment]
I think either of the two would suffice.

**Comment by OrkoHunter** [comment]
I'm thinking in regard of backward compatibility. Let's use `__future__`.

**Comment by yashu-seth** [comment]
So should I change the expressions using float and just add <code>from __ future __ import division</code> ?

**Comment by yashu-seth** [comment]
Okay I have added <code>from __ future __ import division</code>

**Comment by OrkoHunter** [comment]
Please squash the commits into one.
Also, I think all the float functions can entirely be removed.

**Comment by yashu-seth** [comment]
Okay. I have removed the float expressions and squashed the commits into one.

**Comment by OrkoHunter** [comment]
Looks good to me. I'm merging this. We can modify it if there is any change in results.
Thanks @yashu-seth !

**Pull request merged**
