### PR TITLE
Added Gitter Badge and Fix Contribute link

### PR DESCRIPTION
**Pull request by aktech**
@debugger22

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Thanks!

**Comment by debugger22** [comment]
@aktech  Thanks for the PR! The failing test was unrelated. It's a known issue.

@OrkoHunter Thanks for merging.

**Comment by aktech** [comment]
BTW, **build failing** doesn't looks good in any library, It needs to be fixed.
Can you point me to the issue about this?

**Comment by debugger22** [comment]
True that. IIRC this is the one. https://github.com/BinPy/BinPy/issues/256

**Comment by OrkoHunter** [comment]
I saw this on the travis-ci build log

```
Ign http://apt.postgresql.org precise-pgdg/main TranslationIndex
Ign http://apt.postgresql.org precise-pgdg/main Translation-en_US
Ign http://apt.postgresql.org precise-pgdg/main Translation-en
Err http://downloads-distro.mongodb.org dist/10gen Translation-en
  Could not connect to downloads-distro.mongodb.org:80 (23.23.96.15), connection timed out

Fetched 6,059 kB in 11s (545 kB/s)

W: Failed to fetch http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/i18n/Translation-en  Could not connect to downloads-distro.mongodb.org:80 (23.23.96.15), connection timed out

E: Some index files failed to download. They have been ignored, or old ones used instead.

The command "sudo apt-get update" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by aktech** [comment]
@OrkoHunter 
This looks like a timed out. I think probably this is not the exact cause of failure.

**Pull request merged**
