### PR TITLE
Completeley Working gates.py and connector.py with examples

### PR DESCRIPTION
**Pull request by ssr09**
Implemented High Impedance functionality
Logic Contentions will be detected
Corrected many minor bugs in implementation of gates
Rewrote setInput() and setInputs()
Changed the variables related to Connector class
Added a little Documentation
Examples written for all gates and a few exceptions and warnings
Python 3.x compatible (and almost PEP8 compatible)

### CODE REVIEW

**Comment by ssr09** [comment]
@jayrambhia Sorry for the huge amount of changes in a single commit. was forced to work on a system without git and net :/ But, everyting works! run the examples! :)

**Comment by jayrambhia** [comment]
You haven't added tests. Plus, 2 tests are failing. Can't merge this in.

**Comment by ssr09** [comment]
working on displaying the diagram of a gate with its current inputs and outputs (similar to the drawIC_and_pin, i will create draw_gate)

**Comment by jayrambhia** [comment]
No need of draw_gate. First work on essential parts.

**Comment by ssr09** [comment]
which ones? changinWireValue_example is supposed to show an error because it is not allowed

**Comment by jayrambhia** [comment]
Check The Travis Build status!

**Comment by ssr09** [comment]
ok! will review and correct! :)

**Comment by ssr09** [comment]
Done! Test for buffers added and all tests pass. :)

**Comment by ssr09** [comment]
@jayrambhia can you review the code and tell me if there are any other changes that i need to make?

**Comment by ssr09** [comment]
May i know why is this not being merged so that i can do the needful? 
I've handled all the corner cases, fixed all the bugs (that i could find while executing all the examples that have been created) and also added the tristate functionality. 
Is there anything i am missing? or is there any function which does not work as it is needed to? Shall i post the outputs of a few of the examples to show how it is working?

**Comment by jayrambhia** [comment]
Patience you must have my young padawan!

**Comment by ssr09** [comment]
ok! :) 
actually.. i posted that only coz i felt many ppl are working on removing bugs of gates.py and if this merge is done, then, all of us can start working on something else like sequential ckts!

**Comment by salilkapur** [comment]
Nice Work!

One thing though why have you changed the dictionary to two lists in the connector class? We could do with one dictionary. Looks much cleaner.

**Comment by ssr09** [comment]
@salil93 dictionary version implemented in PR #101

**Comment by jayrambhia** [comment]
@SSR09 Rebase and make sure that it is 3.x compatible. There are a lot of changes in the code. Be careful! Send another pull request.

**Pull request closed without merging**
