### PR TITLE
Series_4000

### PR DESCRIPTION
**Pull request by gargshashank5**
Added new file for ICs of 4000 series. Added classes for 4000, 4001, 4002, 4011, 4012, 4023, 4025, 4068, 4069 and 4070.

### CODE REVIEW

**Comment by rajat974** [comment]
You should write tests also.

**Comment by jayrambhia** [comment]
Add some examples too. It looks good. I'll merge it with examples.

**Comment by gargshashank5** [comment]
I created a file examples_series_4000.py. I cannot figure out where to add this. Do I need to create a sub-module examples and place the file there. Or this examples file need to be in ic submodule. Moreover should I add examples for all ICs of 4000 series or a few examples will suffice?

**Comment by jayrambhia** [comment]
Put it in `/examples/ic/Series_4000/` Each file should have name according to the IC. `IC4001.py`, `IC4002.py` etc

**Comment by gargshashank5** [comment]
@jayrambhia please review it. I have added examples for all the ICs in `examples/ic/Series_4000`

**Comment by ghost** [comment]
@gargshashank5 Hey! Pl. remove `print` in line no 8 of every example. It gives u an output None. I made a mistake while adding my examples. rajat corrected it recently. Check this #90

**Comment by gargshashank5** [comment]
@rvraghav93 done.

**Comment by jayrambhia** [comment]
@gargshashank5 I can't merge this directly. Make a new branch from this branch and rebase it to BinPy's develop branch and send another pull request. One more thing, we are trying to keep segregated tests. See this #86. So according to that put these tests in different files and add it in .travis.yml. And make sure that everything is passing.

**Comment by gargshashank5** [comment]
sent new pull request (https://github.com/BinPy/BinPy/pull/112).

**Pull request closed without merging**
