### PR TITLE
Add correct package names of dependencies in README

### PR DESCRIPTION
**Pull request by debugger22**

### CODE REVIEW

**Comment by ghost** [comment]
The ipython-notebook has some [dependencies](http://ipython.org/install.html#) : jinja2, tornado spinx etc ... This is not resolved when installed via apt-get ... could you include this instead `pip install ipython[all]` ?

**Comment by debugger22** [comment]
Are you sure that these dependencies don't get resolved by apt-get?

**Comment by ghost** [comment]
wail il uninstall jinja tornado and sphinx and retry using `apt-get` and tell u in some time !

**Comment by ghost** [comment]
Hey I am not able to completely uninstall its dependencies ... I think i installed using the setup.py file ... and I dont have that source to list the files it installed. 

But I think u are right apt-get would install dependencies too. Sorry for the error :)

Yesterday while testing the notebook with python 3.x I did this `pip3 install ipython` and the dependencies were not met when I used `ipython3 notebook` subsequently after that. Thats y I said that. `apt-get` is fine !

**Comment by ghost** [comment]
But for ipython3 support we might have to include `pip3 install ipython[all]` ! Is ipython3 required since we support both python 2 and python 3 ?

**Comment by debugger22** [comment]
It's just a readme to give a basic idea of the installation. Lets assume
that the user is smart enough to figure it out for python3. :smile:

**Comment by ghost** [comment]
Oki :P

**Comment by ghost** [comment]
One more thing... Why are we having branches other than `develop` like `master` `legacy` etc ... ?

**Comment by rajat974** [comment]
@debugger22  But there is no problem in adding ipython3 for the same I guess

**Comment by debugger22** [comment]
we've kept master just to keep code for the latest release. I'll remove other branches.

**Comment by debugger22** [comment]
Ok I'll add it too.

**Comment by debugger22** [comment]
I tried installing `ipython3-notebook` and it automatically installed dependencies like `python3-zmq` and `python3-tornado`. So I think we should use `apt-get` only.

**Comment by ghost** [comment]
okay ! the one u installed is it ver 2 ?

**Comment by debugger22** [comment]
I already had everything for python2. Now with the commands I've added(just) it's working fine for python 3 also.

**Comment by ghost** [comment]
Nono I am talking about `ipython3 notebook --version` :)

**Comment by debugger22** [comment]
It's `0.13.2`. I installed it from Ubuntu 13.10 repository

**Comment by ghost** [comment]
Its outdated ! Thats y I installed using pip I guess... 
Latest is version 2.

**Comment by debugger22** [comment]
Won't they update it in near future? They still encourage to use `apt-get`. See [this](http://ipython.org/install.html)

**Comment by ghost** [comment]
I guess they wont :P coz after 0.x came 1.x they didnt even update that ... 2.x got released just a few weeks back. And most of the notebooks I will put wont  be working on 0.x :)

Btw Ubuntu 14 will be released today or tomo ... :D

**Comment by debugger22** [comment]
Ok then u send a PR on my fork. :smile:

**Comment by ghost** [comment]
okay ! will do that !

**Pull request merged**
