### PR TITLE
Corrected the examples and rewrote them using IPython Notebook files.

### PR DESCRIPTION
**Pull request by ragv**
1. Examples (.py) in the (old) `examples/` directory have been corrected and rewritten using IPython Notebook file.
2. Corresponding `.ipynb` files are stored in `examples/notebook` and the (old) `.py` files in the `examples/` have been replaced with the cleaner ones as exported from their respective IPython Notebooks and have been moved to `examples/source`.
3. `.rst` files of these IPython notebooks are stored in the directory `docs/source/modules/usage/`.

This is a sample of the rendered IPython file : [BinaryCounter.ipynb](http://nbviewer.ipython.org/gist/rvraghav93/10740725)

### CODE REVIEW

**Comment by debugger22** [comment]
@rvraghav93 Sorry I did not see this PR. I already changed the import issue of the clock. But it has some other good things. Do you mind rebasing it?

**Comment by ghost** [comment]
@debugger22 NP :) How about all the examples in ipython notebook file ... ? this would be easy to execute it step by step and also it wont be necessary to use the `print("CODE")` Users themselves will see both the code and result. ?

There is just one problem, the width of the oscilloscope preview will be lesser about 3/4th of what would be on the screen.

**Comment by debugger22** [comment]
That's a good idea. Can we use some printer to print the oscilloscope output on IPython in a better way?

**Comment by ghost** [comment]
Wait I'll send one example as an ipython notebook. See if the preview there looks okay ?

**Comment by ghost** [comment]
@debugger22 Check these:

Online viewer's [rendering of the ipython notebook.](http://nbviewer.ipython.org/gist/rvraghav93/10740725)

The [rst file](https://github.com/rvraghav93/BinPy/blob/develop/BinPy/examples/Counters/BinaryCounter.rst) converted from that ipynb. [ Can be directly viewed in github ]

This [github-html preview](http://htmlpreview.github.io/?https://github.com/rvraghav93/BinPy/blob/6521f840123c412940e199f57904f4e3a6b6a1e5/BinPy/examples/Counters/BinaryCounter.html) of the html file converted from that ipynb. [ Can be viewed via html preview feature of github i.e http://htmlpreview.github.io/? [HTML FILE URL] ]

and this [.py file](https://github.com/rvraghav93/BinPy/blob/0b1cd33dbd88cf23e3c36fc8e030ef86080c7503/BinPy/examples/Counters/BinaryCounter.py) converted from that ipynb. [ For those who cant install the ipython notebook and its dependencies ]

Check these 4 and tell me what all files do we need to include apart from the `.ipynb` file for each example.

**Comment by debugger22** [comment]
According to me only source and nb files are enough. See [this](https://github.com/sympy/sympy/tree/master/examples/). Including html files doesn't look good to me.

You should create a notebooks folder and put nb files in that folder.

**Comment by ghost** [comment]
Okay ! 
So under examples, we have two folders [ source and notebook ] and under each I will preserve the directory structure which exists in examples [ presently ]. is this okay ?
That is `examples/source/Counters/BinaryCounter.py` and `examples/notebook/Counters/BinaryCounter.ipynb` ...

**Comment by debugger22** [comment]
Yeah!

**Comment by ghost** [comment]
And one more thing .. the `examples/source/Counters/BinaryCounter.py` will look like [this](https://github.com/rvraghav93/BinPy/blob/0b1cd33dbd88cf23e3c36fc8e030ef86080c7503/BinPy/examples/Counters/BinaryCounter.py) and NOT like [this](https://github.com/BinPy/BinPy/blob/develop/BinPy/examples/Counters/BinaryCounter.py) Is that okay too ?

**Comment by debugger22** [comment]
Yes that's even better I think.

**Comment by axiom24** [comment]
That looks good

**Comment by ghost** [comment]
Ok ! Will do the same for all examples within 1 or 2 days :)
EDIT: or 6 or 7 days :P

**Comment by rajat974** [comment]
Great work @rvraghav93

**Comment by ghost** [comment]
rajat, Thanks :D  

30k lines and this is still not over :O

**Comment by debugger22** [comment]
```
./BinPy/examples/source/ic/Series_4000/IC4078.py:25:1: E265 block comment should start with '# '
```

**Comment by ghost** [comment]
Finally done !

**Comment by debugger22** [comment]
Thanks! That's a great job.

**Pull request merged**
