### PR TITLE
Add IC741G86, Add tests for IC741G86

### PR DESCRIPTION
**Pull request by ankitjavalkar**
Modified BinPy/ic/series_7400.py to add class for IC741G86. Modified BinPy/tests/series_7400_tests.py to add tests for the IC741G86

### CODE REVIEW

**Comment by debugger22** [comment]
Please rebase it to remove merge conflicts.

**Comment by debugger22** [comment]
Closing it for now. Please reopen it if you want to continue it.

**Comment by ankitjavalkar** [comment]
Can I know if I can improve this commit in anyway to get this merged OR the reason behind closure? Can I rebase my own fork and try to submit another pull request?
Please suggest.

**Comment by salilkapur** [comment]
Please rebase and send the Pull Request again.

**Pull request closed without merging**
