### PR TITLE
Added test file for series7400ICs and corrected a bug

### PR DESCRIPTION
**Pull request by mohitgujarathi14**
- Created test file for series7400 ICs
- Corrected a bug for IC7445
- updated .travis.yml
- Corrected a bug in AnalogFormulas.py
- Updated AnalogFormulas.py by adding left out cases

### CODE REVIEW

**Comment by rajat974** [comment]
@mohitgujarathi14 I reported you that tests for IC that are merged here are already present in BinPy . It created many duplicate tests.

**Comment by debugger22** [comment]
@rajat974 I think we should split ics_tests.py in different series files otherwise it would get much bigger when other series would be added. I'll remove the duplication and send a PR.

**Comment by rajat974** [comment]
@debugger22  basically ics_tests.py only have series 7400 tests. I think we only need to rename it and nothing  else.

**Comment by mohitgujarathi14** [comment]
Yes . @debugger22 As @rajat974 says just rename the file. For further series, we can make newer ones. Also infact we have separate test file for series4000.

**Pull request merged**
