### PR TITLE
Update sequential.py

### PR DESCRIPTION
**Pull request by vntyadav1228**
DLatch implemented previous DFlipFlop is level triggered Latch

### CODE REVIEW

**Comment by vntyadav1228** [comment]
any review??

**Comment by salilkapur** [comment]
@vntyadav1228 Without changing the 2 input implementation of DFF, can you add the edge triggered feature. With your current change we cannot use a clock with it. If we have 2 inputs then one can be used as a clock along with edge triggered feature.

**Comment by vntyadav1228** [comment]
sure

**Comment by vntyadav1228** [comment]
https://github.com/BinPy/BinPy/issues/113 issue in connector , @salil93

**Comment by ghost** [comment]
@debugger22 - Implemented in merged PR #126 . Can now be closed !

**Comment by debugger22** [comment]
Thanks!

**Pull request closed without merging**
