### PR TITLE
Setting the clock to a uniform value of 500

### LINKED ISSUE #192: Tests fail occasionally
Similar to https://github.com/BinPy/BinPy/issues/188 even this test failed recently. Passed after a restart.

```
FAIL: BinPy.tests.counters_tests.test_NBitDownCounter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/BinPy/BinPy/BinPy/tests/counters_tests.py", line 47, in test_NBitDownCounter
    0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1]
AssertionError
```

Here the clocks are also being killed.

### PR DESCRIPTION
**Pull request by ragv**
This is an attempt to fix #192

### CODE REVIEW

**Comment by rajat974** [comment]
I think this should work. Or Can we make a single clock for whole of the file to make less no of threads?

**Comment by ghost** [comment]
I think that is even better ... Also how about a single clock ( perhaps 2 ) for the entire BinPy ?

**Comment by debugger22** [comment]
Is the clock not being killed after calling `kill()`?

**Comment by rajat974** [comment]
@debugger22 No, it is killed, but since we are creating threads, then it might be using value from main tests because we are using same names for clock with different frequencies.

**Comment by ghost** [comment]
Hey ! I dont think that is the issue ... [ Since every clock is created using the constructor, the clock objects do not point to the same reference ]

If you are unsure do `print(id(clk_variable_name))`.

## My understanding of this issue is something like this:

## Main Thread.

0.0000          Main Thread object checks for clock.
0.00012        Main Thread object checks for clock.
0.00021        Main Thread object checks for clock.     <------- Error occurs here.

Specifically in counters:
[Not very accurate description, I agree ... This is just for visualisation of the error ]

Assume Flip Flop's Clock history is 1

0.0004          Counter Waits until 0.
0.0005          Counter Waits for 0 and finds 0. ----> Triggers Flip Flop.
0.0006          Flip Flop Checks for 1 to 0 Transition. In ideal case This should happen at
                     t < 0.0005999 when clk remains at 0.
                    Since this is delayed, (say due to heavy load in cpu by other processes)
                    **The Flip Flop does not change its state, when in ideal case it ought to have 
                      changed.**

## Clock Thread [ Ought to change every 0.0001 second, assume 10000 Hz]

0.0000          clk is 1
0.00011        clk is 0   <------- Error occurs here.
0.0002          clk is 1
0.0003          clk is 0

0.000394      clk is 1
0.000495      clk is 0
0.000599      clk is 1    <------- Error occurs here.

This explains the random nature of the error too, I guess.
This is the same issue with distortions in the oscilloscope.

Refer this http://www.tutorialspoint.com/python/python_multithreading.htm article
on synchronization of threads in multithreaded environment.

This can be undone using locking concept of multithreading. But in BinPy I
dont think we can do that since we cannot assume our users to know thread
locking and all. We need a work around.

Suggestions ?

On Sun, Apr 13, 2014 at 7:04 PM, Rajat Aggarwal notifications@github.comwrote:

> @debugger22 https://github.com/debugger22 No, it is killed, but since
> we are creating threads, then it might be using value from main tests
> because we are using same names for clock with different frequencies.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/BinPy/BinPy/pull/193#issuecomment-40307722
> .

## 

Raghav Rv

**Comment by ghost** [comment]
@debugger22 Why is this one not merged ? The above comment and its patch might take a lot of time and discussion to fix. Meanwhile we could have a uniform clock for now ?

**Comment by debugger22** [comment]
I was just waiting for more errors but didn't get any. Anyway this is good.

**Comment by debugger22** [comment]
Thanks!

**Pull request merged**
