### PR TITLE
Added class IC_7406

### PR DESCRIPTION
**Pull request by Rapternmn**
Added this class in series 7400.py
This is my first pull request ever.
I hope everything is fine.If there is any mistake,please tell me,i would like to keep on contributing!
Thank you

### CODE REVIEW

**Comment by ghost** [comment]
Hi @Rapternmn ! It looks good ... See if you can add a test. go to `tests/test_series_7400.py` to see examples.

**Comment by Rapternmn** [comment]
Okkk.

**Comment by ghost** [comment]
The pep8 test fails... Check [this](https://github.com/BinPy/BinPy#how-to-contribute) to see how you can resolve pep8 issues.

**Comment by ghost** [comment]
Looks good to me ... Seems to have included a few pep8 changes too ... 
@debugger22 review !

**Comment by Rapternmn** [comment]
Should i continue expanding 7400 series..there is a lot more to be done i
guess..

**Comment by ghost** [comment]
@Rapternmn Yea feel free to !

**Comment by ghost** [comment]
Thanks!

**Pull request merged**
