### PR TITLE
Added IC7420 and 7421

### PR DESCRIPTION
**Pull request by Lordie12**
Added IC7420 and 7421

### CODE REVIEW

**Comment by axiom24** [comment]
please create a branch FSM-dev for the repo in your laptop, then change the branch to FSM-dev and you will notice in the file that these IC's have already been added. So we cannot merge this request. Sorry for that.

**Comment by Lordie12** [comment]
ohh ok, sorry, im not so used to github , used to work with svn a lot

**Comment by axiom24** [comment]
ohh no problem :)

**Comment by Lordie12** [comment]
guess I need to learn it a bit more :P

**Pull request closed without merging**
