### PR TITLE
Implemented Clock

### PR DESCRIPTION
**Pull request by ssr09**
Split digital.py to clock.py and digital_display.py
Updated the Clock class
Added functionality of connecting to and disconnecting from clock
Changed implementation of Connector.connections to dict

### CODE REVIEW

**Comment by jayrambhia** [comment]
Add tests and examples.

**Comment by ssr09** [comment]
Done! :)

**Comment by ssr09** [comment]
@jayrambhia  Pls review! :)

**Comment by jayrambhia** [comment]
@SSR09 Rebase and make sure that it is 3.x compatible. There are a lot of changes in the code. Be careful! Send another pull request.

**Pull request closed without merging**
