### PR TITLE
Adders, Subtractors added , IC4027, 4028, 4029 added, Examples with all new functions.

### PR DESCRIPTION
**Pull request by rajat974**
- Binary Adder, Half subtracter, full subtracter, binary subtracter added.
- error due to __repr__in gates corrected

```
>>> OR(AND(0, 1), 0)
1
```
- Changed `backtrack` to `Tree` class, so that we can have forward traversing also and can show tree for forward traversal, tests changed, Examples added
- Changed 2-bit Binary Counter to n-bit counter, so that it can also serve the purpose of UP counter
- Extra functions in TFlipFlop removed which were creating problem due to overriden functions from JKFlipFlop
- Corrected parseEquation.py, Added its tests and examples.

```
Expr('(A & B)').parse()
Invalid Arguments
```
-  Examples added for new classes, Adders, Subtractors, Octal counter, stage14counter, connector, expr etc.
- Examples for Combinational devices and gates corrected, added **repr** and **call** type examples
- Refactored examples for counters, and sequential circuits, added examples of all its varied functions like `setInputs`, `setOutputs`, `setCounter`, `resetCounter` etc.
- Added IC 4027, 4028, 4029 related to counters and sequential circuits, with tests.
- Added tests which were not added in `.travis.yml` , `print_tests`, `backtrack_tests` etc.

Now almost all of the features of BinPy has examples.

### CODE REVIEW

**Comment by rajat974** [comment]
@jayrambhia I had removed the pep8 from this. 
But for pep8, my point was like each time we have to indent it again, isn't it better that developer checks its pep8 before pushing. Like here also, pr 162 merged was not pep8 compatible, This way the repo will always be pep8 compatible. and this is not so harsh. I had provided the command in #161 where it can be done with a single command. Anyway, I will send a separate pr for that.

**Comment by jayrambhia** [comment]
PEP8 aside. This is some good work, but you need to rebase.

**Comment by rajat974** [comment]
More changes to be added.

**Comment by rajat974** [comment]
@jayrambhia  Please review it now !

**Pull request merged**
