### PR TITLE
Corrected docs to make oscilloscope appear correctly in the sphinx documentation

### PR DESCRIPTION
**Pull request by ragv**
@debugger22 Pl. review ! The docs are corrected now ...

### CODE REVIEW

**Comment by debugger22** [comment]
75 seems good.

**Comment by debugger22** [comment]
Could you also correct examples for Counters?

**Comment by ghost** [comment]
@debugger22 done ! I accidentally deleted this commit previously while trying to delete the commit of an unfinished stash ;(

**Comment by debugger22** [comment]
Thanks!

**Pull request merged**
