### PR TITLE
Connector can't serve output for multiple devices+ Addition of new ICs + Adders + Registers

### PR DESCRIPTION
**Pull request by rajat974**
- Change in output functionality of connector
- Addition of `preset` and `clear` option in flip flops
- Addition of IC 7470, 7472, 7473, 7474, 7475, 7476, based upon sequential circuits with tests.
- Addition of Half-Adder , Full Adder
- `self.setIC()` added on trigger
- IC 4008 4013 added
- Registers Implemented - 4Bit Register, Load Register, Shift Register
- Registers related Ics IC 4015, 4017
- Bug Fixed in BinPy Shell
- 14,8 stage counter, Ring/Johnson counter
- IC 4009, 4010, 4019, 4020, 4022

### CODE REVIEW

**Comment by rajat974** [comment]
@salil please review it .

**Comment by rajat974** [comment]
@salil93  I have added many things and want you to have a review so that I can work on more things  based upon these.

**Comment by jayrambhia** [comment]
Please rebase.

**Comment by rajat974** [comment]
@jayrambhia Please see, its done !

**Pull request merged**
