### PR TITLE
Negative Numbers error corrected

### PR DESCRIPTION
**Pull request by rajat974**

### CODE REVIEW

**Comment by salilkapur** [comment]
What you are trying to do is fine, but do we really use the '-' symbol with binaries? I mean I can see a  '-10' as an output of one of your tests. For negative numbers we use 2's compliment representation. 

What is the functionality/feature that you are aiming at here?

**Comment by rajat974** [comment]
@salil93 basically we can have both positive and negative numbers, but for that we have to make some standard for whole of the BinPy codebase so that every new implementation will be on that basis. I discussed this @jayrambhia and i found errors in this code, so i corrected with putting '-' sign. 
The motivation for this is to ease the handling of four different cases , unsigned, and signed complements, so its better to use '-' sign. because in BinPy codebase, the kind of functionalities we will handle will suffer thiese kind of cases very rare, because BinPy is not dealing with computer representation. So acc. to me '-' is better.
If you have better idea, we should discuss and make something as a standard.

**Comment by salilkapur** [comment]
What kind of errors are we talking about here? 

As far as I understand, I think we can leave it for the users to comprehend the sign of the number. All operations should take place as they do for binary numbers. If the user wants to do signed operations then s/he can treat the binaries as 2's compliments.

**Comment by debugger22** [comment]
@rajat974 why would any input will be given using decimal numbers to these functions? They can easily be added using simple operators. These functions were introduced just to handle binary numbers(output of a part of circuit).

**Comment by rajat974** [comment]
@salil93 What if we subtract 1 from 0 ?   SUB(00, 01), this will give a negative number. This motivated me for such kind of implementation.
@debugger22  Ya ! even i am not allowing the decimal numbers, they are just 1 in negative form of binary.

**Comment by rajat974** [comment]
I removed '-' . please review it again!

**Pull request merged**
