### PR TITLE
Made some minor changes to the gates.py file.

### PR DESCRIPTION
**Pull request by petermlm**
I've made a few changes to the gates.py files, the one which implements the various logic gates, which would close issue #79, if accepted.

The changes are small details, they are:
- The "self.history_active" attribute of class "GATES" is now a Boolean, which might be more readable then it's integer counterpart. Also, the function "setHistoryActive(val)" is now implemented. This function takes a Boolean as a parameter, which then becames the value of self.history_active.
- The class MIGATES was implemented, which stands for Multi Input Gates. It is now the parent class for all the gates that have more than one input and it serves to have a common constructor instead of it being repeated throughout the code.

### CODE REVIEW

**Comment by jayrambhia** [comment]
@petermlm you need to rebase.

**Comment by petermlm** [comment]
@jayrambhia, is it ok now?

**Comment by jayrambhia** [comment]
@petermlm I tried merging your code fixing the issues. But 3 tests are failing.

``` shell

======================================================================
ERROR: BinPy.tests.combinational_tests.MUX_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jay/Projects/AdminProjects/BinPy/BinPy/tests/combinational_tests.py", line 6, in MUX_test
    mux.selectLines(0)
  File "/home/jay/Projects/AdminProjects/BinPy/BinPy/Combinational/combinational.py", line 38, in selectLines
    self._updateConnections(self.selects)
AttributeError: MUX instance has no attribute '_updateConnections'

======================================================================
ERROR: BinPy.tests.combinational_tests.DEMUX_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jay/Projects/AdminProjects/BinPy/BinPy/tests/combinational_tests.py", line 44, in DEMUX_test
    demux.selectLines(0)
  File "/home/jay/Projects/AdminProjects/BinPy/BinPy/Combinational/combinational.py", line 114, in selectLines
    self._updateConnections(self.selects)
AttributeError: DEMUX instance has no attribute '_updateConnections'

======================================================================
ERROR: BinPy.tests.sequential_tests.test_SRLatch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jay/Projects/AdminProjects/BinPy/BinPy/tests/sequential_tests.py", line 8, in test_SRLatch
    testLatch.setInputs(0, 0)
  File "/home/jay/Projects/AdminProjects/BinPy/BinPy/Sequential/sequential.py", line 26, in setInputs
    self.g1.setInput(0, R)
  File "/home/jay/Projects/AdminProjects/BinPy/BinPy/Gates/gates.py", line 56, in setInput
    self.inputs[index] = value
TypeError: 'tuple' object does not support item assignment

----------------------------------------------------------------------
Ran 61 tests in 0.028s

FAILED (errors=3)
```

I think you should add this code in the current develop branch because there have been some significant changes.

**Comment by petermlm** [comment]
Ah ok. I'll get on that

**Comment by jayrambhia** [comment]
Here's the merged file http://pastebin.com/4JLVf8ZS

**Pull request closed without merging**
