### PR TITLE
binToDec and decToBin are now working with floating point binary numbers

### LINKED ISSUE #152: Operations bug
binToDec and DecTobin works only for integer values not for floating point types

### PR DESCRIPTION
**Pull request by krngrvr09**
fixes #152

### CODE REVIEW

**Comment by salilkapur** [comment]
Nice work here.

Add tests for these functions and then we can merge this in.

**Comment by krngrvr09** [comment]
Thanks @salil93 . I was wondering, if in `binToDec` function, we don't take string as an input. Instead of '1001', we take 1001 as input, and convert that to string in the function definition. It would be easier for the users. What do you think? 
I just realized 2 comments slipped through, in the commit. I'll remove them too.
I'll also make it consistent with the PEP-8 convention.

**Comment by rajat974** [comment]
@krngrvr09 we can handle both the cases

**Comment by krngrvr09** [comment]
Alright. I'll write the tests right away.

**Comment by salilkapur** [comment]
@krngrvr09 Yes, that could be done. In fact we could keep both the implementations. For strings and numbers both. For direct numbers we will have to take care of the fact that the user should only use 0 and 1 and no other digit. Try if you can add this too.

**Comment by krngrvr09** [comment]
@salil93 Everything done. Can you tell me how to test, if a function raises an exception. Should I use `unittest.TestCase`? Also, how do I run tests locally? `python setup.py test`? It doesn't seem to be working.

**Comment by rajat974** [comment]
Run nosetests and nosetest3 in your BinPy folder

Rajat Aggarwal
IIITH

**Comment by salilkapur** [comment]
@krngrvr09 Go to `BinPy/BinPy/tests` and run `nosetests <filename>.py` where `<filename>` is your tests file.

**Comment by krngrvr09** [comment]
Thanks @salil93 @rajat974 . Its working. It still doesn't support the direct numbers, because converting from floating point to strings has some precision factor involved. Also python inteprets a number prefixed with '0' as octal. Eg. `print 011`, prints 9. So, I think you should merge it, if everything is ok. What do you say?

**Comment by debugger22** [comment]
@krngrvr09 We can add one more feature to parse a list as binary number and return its decimal.

```
>>> binToDec([1, 0])
2
```

**Comment by krngrvr09** [comment]
Ok, I can add that. But don't you think, it would be easier for users to enter the string. But, yes, input can be coming from any source, not just the user. One thing, We wouldn't be able to work with floating point binary numbers, in lists. But yes, they can be an additional feature.

**Comment by krngrvr09** [comment]
I think everything is working fine. Anything else?

**Comment by debugger22** [comment]
@jayrambhia I think it is good to go, any comments?

**Pull request merged**
