### PR TITLE
Bus

### PR DESCRIPTION
**Pull request by salilkapur**
Bus objects can be used where a lot of connectors are need. It will make the code cleaner and easy to understand.

### CODE REVIEW

**Comment by debugger22** [comment]
I am travelling now. Will add tests later.

**Comment by ghost** [comment]
This is perfect ... we could use the bus as an interface betw any 2 modules ( like StepperMotors' `leads` ... Dont merge this till 3 am ... Ill add a few enhancements ...

**Comment by debugger22** [comment]
Yea. Don't worry, it still needs some tests.

**Comment by ghost** [comment]
@debugger22 ill take care of it ! :)

**Comment by debugger22** [comment]
Thanks!

**Comment by debugger22** [comment]
Does anyone know how to configure coveralls? I am failing to do so.

**Comment by debugger22** [comment]
http://us.archive.ubuntu.com/ubuntu/pool/main/q/qt4-x11/qt4-designer_4.8.1-0ubuntu4.6_amd64.deb is giving 404 error. @rvraghav93 Should we comment out Qt installation/tests?

**Comment by ghost** [comment]
@debugger22 Since we will be having a separate repo for GUI we could remove it altogether ...

**Comment by debugger22** [comment]
Even after failing many tests, travis is showing "passed". How?

**Comment by salilkapur** [comment]
What tests are failing?

**Comment by debugger22** [comment]
Just one. Pushing it now.

Regards
Sudhanshu Mishra

**Comment by debugger22** [comment]
Merging this for now. I'll fix styling issues in a different PR.

**Pull request merged**
