### PR TITLE
connector trigger() added

### PR DESCRIPTION
**Pull request by rajat974**
- The implementation doesn't `trigger()`  in `connector` class which is supposed to be. 
- Inconsistent path in `README`

### CODE REVIEW

**Comment by rajat974** [comment]
@debugger22 will add more changes soon. plz dnt merge for now

**Comment by axiom24** [comment]
@rajat974 will you continue with this PR? otherwise we can merge it if you are finished :)

**Comment by rajat974** [comment]
Yes ....
There is some wrk to do with this.

Rajat Aggarwal
IIITH

**Comment by axiom24** [comment]
ok , also see that there have been some changes in the repo due which there are some conflicts. Just rebase before continuing further work.

**Comment by rajat974** [comment]
Yes I will

Rajat Aggarwal
IIITH

**Comment by salilkapur** [comment]
Is this resolved now?

**Comment by ghost** [comment]
Closing this for now ! Kindly re-open once you restart your work :)

**Pull request closed without merging**
