### PR TITLE
Modified base.py to include and use pin class and drawIC() method

### PR DESCRIPTION
**Pull request by ragv**
**1. Created a Pin class:**
- Recognizes states as logic objects which have overloaded operators `&`,`|`,`+`,`~` and `^` .
  These operators maps to the BinPy's logic gates AND, OR, OR, NOT and XOR respectively <br> MOTIVATION: Allows fast implementations of ICs by use of these operators rather than specifying the function every time.
- Includes provision to specify `pin_tag` a 3 letter tag for every pin.
- Includes `__call__()` method which can be called to return the state of the pin.

**2. Created `drawIC()` method inside IC class:**
- Visually prints the pin configuration of the particular IC along with its current state.
- Displays a pin_tag for each pin if available.
- Displays the IC No at the center of the IC ( vertically downwards )
- Is compatible with both pin class implementation of IC pins and list implementation of IC pins.

**3. Created 4000 series IC's based on discussions with @debugger22 and @livingstore**

**4. Created IC 4081 and IC 4082 to portray the functionalities of Pin class.**

**5. Added tests for IC 4081 and IC 4082.**

Pl review and let me know if any changes are to be made.

### CODE REVIEW

**Comment by jayrambhia** [comment]
This looks good. Just add some examples and show me how it works.

**Comment by ghost** [comment]
```
In [10]: ic = IC_4082()

In [11]: ic.drawIC()


               _________ ________  
              |         U       |
              |                 |
 Q1  [Z]   ---|  1           14 |---   [1] VCC
              |                 |
              |                 |
 A1  [0]   ---|  2     4     13 |---   [0] Q2 
              |                 |
              |                 |
 B1  [0]   ---|  3     0     12 |---   [0] A2 
              |                 |
              |                 |
 C1  [0]   ---|  4     8     11 |---   [Z] B2 
              |                 |
              |                 |
 D1  [0]   ---|  5     2     10 |---   [Z] C2 
              |                 |
              |                 |
 NC  [0]   ---|  6            9 |---   [0] D2 
              |                 |
              |                 |
 GND [0]   ---|  7            8 |---   [0] NC 
              |                 |
              |_________________|  

In [12]: ic.setIC({2:1,3:1,4:1,5:1,12:1,11:1,10:1,9:0})

In [13]: ic.run()
Out[13]: {1: 1, 13: 0}

In [14]: ic.drawIC()


               _________ ________  
              |         U       |
              |                 |
 Q1  [1]   ---|  1           14 |---   [1] VCC
              |                 |
              |                 |
 A1  [1]   ---|  2     4     13 |---   [0] Q2 
              |                 |
              |                 |
 B1  [1]   ---|  3     0     12 |---   [1] A2 
              |                 |
              |                 |
 C1  [1]   ---|  4     8     11 |---   [1] B2 
              |                 |
              |                 |
 D1  [1]   ---|  5     2     10 |---   [1] C2 
              |                 |
              |                 |
 NC  [0]   ---|  6            9 |---   [0] D2 
              |                 |
              |                 |
 GND [0]   ---|  7            8 |---   [0] NC 
              |                 |
              |_________________|  


```
1. `IC_4082` was created using `Pin` class
2. `ic.drawIC()` is shown above.

This will work for non-Pin class IC's too :  

```

In [26]: from BinPy import *

In [27]: ic = IC_7400()

In [28]: ic.drawIC()


               _________ ________  
              |         U       |
              |                 |
     [0]   ---|  1           14 |---   [0]    
              |                 |
              |                 |
     [0]   ---|  2     7     13 |---   [0]    
              |                 |
              |                 |
     [Z]   ---|  3     4     12 |---   [0]    
              |                 |
              |                 |
     [0]   ---|  4     0     11 |---   [Z]    
              |                 |
              |                 |
     [0]   ---|  5     0     10 |---   [0]    
              |                 |
              |                 |
     [Z]   ---|  6            9 |---   [0]    
              |                 |
              |                 |
     [0]   ---|  7            8 |---   [Z]    
              |                 |
              |_________________|  

In [29]: ic.setIC({1:1,2:0,4:0,5:0,7:0,10:1,9:1,13:0,12:0,14:1})

In [30]: ic.run()
Out[30]: {3: 1, 6: 1, 8: 0, 11: 1}

In [32]: ic.setIC(ic.run())

In [33]: ic.drawIC()


               _________ ________  
              |         U       |
              |                 |
     [1]   ---|  1           14 |---   [1]    
              |                 |
              |                 |
     [0]   ---|  2     7     13 |---   [0]    
              |                 |
              |                 |
     [1]   ---|  3     4     12 |---   [0]    
              |                 |
              |                 |
     [0]   ---|  4     0     11 |---   [1]    
              |                 |
              |                 |
     [0]   ---|  5     0     10 |---   [1]    
              |                 |
              |                 |
     [1]   ---|  6            9 |---   [1]    
              |                 |
              |                 |
     [0]   ---|  7            8 |---   [0]    
              |                 |
              |_________________|  

In [34]: 

```

**Comment by jayrambhia** [comment]
This is brilliant! Can you do one more thing and add some examples? Great work!

**Comment by ghost** [comment]
Thanks !!! sure ! one more pin class ic rite ??

**Comment by jayrambhia** [comment]
You can do that later. I need some examples showing the usage of what you just added. Make a folder in named examples in Binpy. In that add a folder named ic (ic submodule). And add an example for each class that you added.

**Comment by ghost** [comment]
@jayrambhia Added! Please check this out and let me know if this is okay ....

**Comment by jayrambhia** [comment]
Oh! this is good. But I didn't mean examples as README files. I meant python files. so it just shows how to use them. Are you getting my point?

**Comment by ghost** [comment]
oh okay !! will do in some time !

On Sat, Mar 1, 2014 at 7:11 PM, Jay Rambhia notifications@github.comwrote:

> Oh! this is good. But I didn't mean examples as README files. I meant
> python files. so it just shows how to use them. Are you getting my point?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/BinPy/BinPy/pull/68#issuecomment-36424936
> .

## 

Raghav Rv

**Comment by ghost** [comment]
how about this one ? or is it better to have one python script per IC ?

**Comment by jayrambhia** [comment]
Whoa! That was quick. But I guess one code per IC would be better.

**Comment by ghost** [comment]
@jayrambhia Done!! Pl review !
btw I also made a small script to automate this work ... should I include it in a separate folder `/dev/` for use in the future ?

**Comment by jayrambhia** [comment]
Amazing work!

**Comment by jayrambhia** [comment]
@rvraghav93 I want you to do another thing. Shift all these examples files in `/examples/ic/Series_7400/` Each file should have name according to the IC. `IC7401.py`, `IC7400.py`, etc

**Comment by ghost** [comment]
done :) see PR #87 !

**Pull request merged**
