### PR TITLE
An attempt to fix #203

### LINKED ISSUE #203: Make ImplementBooleanFunction accept parameters
Rather than making [ImplementBooleanFunction](https://github.com/BinPy/BinPy/blob/develop/BinPy/Algorithms/ImplementBooleanFunction.py) interactive we should pass parameters to this function

### PR DESCRIPTION
**Pull request by debugger22**
Fixes https://github.com/BinPy/BinPy/issues/203

@rvraghav93 Please review this.

### CODE REVIEW

**Comment by debugger22** [comment]
I haven't added tests though. Will add in some time.

**Comment by debugger22** [comment]
I don't understand why `ExpressionConvert` couln't be found.

**Comment by ghost** [comment]
This is great ! Could you also add an example ?
and about the import I googled it up and got [this](http://stackoverflow.com/questions/12229580/python-importing-a-subpackage-or-submodule). Seems incremental imports dont work ...

**Comment by debugger22** [comment]
I'll add tests and examples.

I never changed anything related to imports. It was working earlier.

**Comment by ghost** [comment]
Earlier `ImplementBooleanFn` was not imported via `__init__.py` and so was not available when we do `from BinPy import *`

But one thing I dont understand too is why is it not raising an error when I manually do `from BinPy.Algorithms.ImplementBooleanFunction import *` instead of letting `__init__.py` do the same ! Wierd !

Try importing like [this](https://github.com/debugger22/BinPy/blob/ibf_int_to_func/BinPy/Algorithms/MooreOptimizer.py) ?

**Comment by ghost** [comment]
Hey one more thing ... can you finalize #190 . If you do, then we can start implementing the same from every PR from now on... rather than refactoring the codebase separately.... and when u do please rename this `ImplementBooleanFn` accordingly - either as implementBooleanFn or as `implement_boolean_fn` :) or in 2 words we can have `boolean_function()` or `make_boolean()` ?

**Comment by debugger22** [comment]
So let's start changing according to new naming convention. `make_boolean` sound good to me.

**Comment by ghost** [comment]
great then !

On Tue, May 6, 2014 at 4:28 PM, Sudhanshu Mishra
notifications@github.comwrote:

> So let's start changing according to new naming convention. make_booleansound good to me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/BinPy/BinPy/pull/227#issuecomment-42288600
> .

## 

Raghav Rv

**Comment by debugger22** [comment]
@rvraghav93 Please see now. I've added tests also.

**Comment by ghost** [comment]
Perfect ! can be merged ... ! :)

**Pull request merged**
