### PR TITLE
WIP: Micro Processor - Intel 8085

### PR DESCRIPTION
**Pull request by ragv**
##### Work Plan

Since this is the 1st microprocessor that will be implemented, the implementation should focus on code re usability and modularity.
##### To do
- [ ] Create a base Microprocessor class with basic functionality to derive from.
- [ ] Create a microprocessor_modules module with a pool of commonly usable modules to derive from for implementing microprocessors. ( ALU - generic, RAM model - generic, Cache Model - generic etc ... )
- [ ] Write extensive tests for all the microprocessor_modules
- [ ] Create uP_8085 class.
- [ ] Find other libraries / codes which implement the same and steal from them ( as permitted by their licence ) - Stupid as it may sound this is very important since It helps to avoid re-inventing the wheel.
- [ ] Write extensive tests for uP_8085
- [ ] Make uP_8085 accept opcode and change its state ( run ) accordingly.
- [ ] Modify test to allow programming of the up_8085
- [ ] Make a .py and .ipynb example file for this Microprocessor.

### CODE REVIEW

**Comment by axiom24** [comment]
@rvraghav93 looks great :)

**Comment by ghost** [comment]
@sarwarc Thanks :D

**Comment by debugger22** [comment]
Folder name like `mups` or `mup` would be better.

**Comment by ghost** [comment]
I'm closing this for now .... Will re-open at a later time :)

**Pull request closed without merging**
