### PR TITLE
Reimplemented gates from scratch. Added states functionality.

### PR DESCRIPTION
**Pull request by JBeCast**
Note: this is more like a huge proposal than a pull request, since if accepted, everything based on gates will have to be reimplemented, but it should be easier though, and I'm definitely willing to collaborate. I tried to follow the DRY principle as much as I could. I'll post working examples here.

Description:
- Consistency: gates now only accept connectors as inputs and outputs.
- Implemented well defined states: (0,1,2,3) as logical 0 and 1, hi-z and undefined respectively, and a validating function.
- Connectors now validate the input. Default state is undefined (3).
- Gates now work with any combination of input states, including undef and hi-z.
- One trigger to rule them all: no more over 9000 triggers.
- Migates mitigated: there's only GATES class now.
- (Already implemented) You should be able to assign an initial state to the connector. This way you could easily create a power source or ground connection and connect every element you need to it, e.g: gnd = Connector(0). This initial state is also validated.
- You can now change a connector state and trigger it easily with the set method. It also checks for possible shortcuts or undefined states, returning an undefined state if something goes wrong.
- Implemented disconnect method for gates. It removes every reference to the gate any connector has. It can be very useful to clean things before removing a gate. Previously, multiple references to the same gate objects could accumulate when reconnecting.
- Implemented connect method for gates. Since this is not something you want to do often, it is the only method that allows you to change connections or even add or remove as many as you want, and you'll have to specify every connector. It previously cleans everything up by calling the disconnect method.
- You'll have as many additional connectors as your circuit has, but that's good. You better give your inputs an adequate name, right? And you definitely can't give a name to the actual gate inputs.
- Leave tapping to Eddie Van Halen (or the gates in this case): Users should be discouraged from using the connector's tap method indicriminately, let the gates manage the connections network instead.
- Gates file now takes about half the ammount of code lines =).
- One more suggestion: I think it's about time to define some common exceptions.
- And another one: gates and connectors should accept a name as argument, and should also have a method to access it and easily check the connections of the circuit (I was about to implement it but didn't have time yet).

### CODE REVIEW

**Comment by JBeCast** [comment]
Here's a slightly humorous approach to implementing a simple XOR gate with NAND gates, from an "average user" perspective:

BEFORE:

```
"""
Previously on BinPy...
After seeing how cumbersome it is to change gate inputs (was it the first one
that was connected to a connector?) and how pretty much impossibru to check
connections (Object at 0x700FECE5? Here be dragons!), our average user
experiences an epiphany and realizes it's much better to use connectors as inputs.
"""
A = Connector()
B = Connector()
Q = Connector()
c1 = Connector()
c2 = Connector()
c3 = Connector()
g1 = NAND(A, B)
g2 = NAND(A, c1)
g3 = NAND(c1, B)
g4 = NAND(c2,c3)
g4.setOutput(Q)
g3.setOutput(c3)
g2.setOutput(c2)  # THIS IS GETTIN' OLD...
g1.setOutput(c1)  # WHY U NO ASKED ME BEFORE!
A.state = 0
B.state = 0
A.trigger()
print(Q.state)
B.state = 1
B.trigger()
print(Q.state)
A.state = 1
A.trigger()
print(Q.state)
B.state = 0  # IF I COULD ONLY DO THIS THINGY IN 1 STEP...
A.trigger()  # I FEEL MISERABLE, BUT AT LEAST MY BELOVED XOR WORKS =)
print(Q.state)
```

NOW:

```
A = Connector(0)
B = Connector(0)  # Now I can haz initial state =)
Q = Connector()
c1 = Connector(0)  # Dude, batched connectors creation wouldn't
c2 = Connector(0)       # be a bad idea either...
c3 = Connector(0)
g1 = NAND(c1, A, B)  # a single output followed by as many inputs
g2 = NAND(c2, A, c1)  # as I want. I now know I MUST use connectors.
g3 = NAND(c3, B, c1)
g4 = NAND(Q, c2,c3)  # Done! No OVER 9000 setOutput! =)
print(Q.state)  # 0 XOR 0 = 0, so far so good...
A.set(1)  # No state n trigger thing, I'm gettin' emotional...
print(Q.state)  # 1 XOR 0 = 1. Yay!
B.set(1)  # OH MY GAWD I just love this set thingy...
print(Q.state)  # 1 XOR 1 = 0. One more to go...
A.set(0)
print(Q.state)  # 1 XOR 0 = 1. OMG!
"""
Our average user has just succeeded at life. He/she walks into an epic
sunset, determined and strong.
"""
```

**Comment by JBeCast** [comment]
One more not too serious example:

```
A = Connector()
B = Connector()
Q = Connector()
g1 = XOR(A, B, Q)  # Oops! Output goes first!
g1.connect(Q, A, B)  # No harm done...
# Magic goes in the background and everything gets happily rewired.

print g1.getStates()  # {'inputs': [3, 3], 'output': 3} Initial state undefined
A.set(0)
print g1.getStates()  # {'inputs': [0, 3], 'output': 3} So far, so good...
B.set(0)
print g1.getStates()  # {'inputs': [0, 0], 'output': 0} It's alive!
B.set(1)
print g1.getStates()  # {'inputs': [0, 1], 'output': 1} XORING like a boss...
A.set(1)
print g1.getStates()  # {'inputs': [1, 1], 'output': 0} Karnaugh style!
B.set(0)
print g1.getStates()  # {'inputs': [1, 0], 'output': 1} Pretty much an XOR...
```

**Comment by JBeCast** [comment]
And yet another one...

```
# Build your own SR latch in 5 easy steps:
S = Connector()
R = Connector()
Q = Connector()  # Yes, it works with all undefined initial values.
nQ = Connector()
g1 = NOR(Q, R, nQ)
g2 = NOR(nQ, S, Q)
# Voilà! C'est finit! Très bien! I ran out of french!
# Remove previous comment if you're gonna run this or non ASCII chars may explode.

print Q.state, nQ.state  # 3 3. Here be dragons, as expected.
S.set(0)
print Q.state, nQ.state  # 3 3. Gimme something else...
R.set(0)
print Q.state, nQ.state  # 3 3. Stubborn (0,0) holding whatever was there before.
S.set(1); S.set(0)  # Time to earn my badge as a proper SR latch...
print Q.state, nQ.state  # 1 0. Yay!
R.set(1); R.set(0)
print Q.state, nQ.state  # 0 1. Reset also works!
R.set(1); S.set(1)  # The one and only, the most feared, the forbidden state!
print Q.state, nQ.state  # 0 0. I told you not to play with that...
R.set(0); S.set(1)
print Q.state, nQ.state  # 1 0. And back on business...
```

**Comment by JBeCast** [comment]
I didn't get the point of the whole "history" mess. Was it to emulate edges? If so, this can be more easily implemented in the Connector class now, since only connectors carry signals from and to gates.

**Comment by salilkapur** [comment]
"history" mess was for feedback circuits or circuits which have loops in them. If the inputs are same as the history then we do not trigger the circuit element.

**Comment by JBeCast** [comment]
@salil93 If it's only for one gate, I thought about simply making sure the output connector is not in the input connectors list. I'll also review it in detail by making intentional loops. Thanks for the feedback =).

**Comment by JBeCast** [comment]
Added tests for the gates including hi-z and undefined states. Also added a multiple reconnection test. Notice how you can mess up with the connections and nothing goes wrong. I know it's quite a lot of code to review, but any feedback will be appreciated.

**Comment by JBeCast** [comment]
@salil93 @debugger22 @jayrambhia @abhinavgupta This is too much to fit in here, and since right now we're on the GSoC inscription period, I understand you're probably too busy to review it.
If I'd been in your place, I'd probably have torn my hair out with so much activity and pull request bombing.
I'll try to thoroughly review the pros and cons of my proposal and expose them as briefly and clearly as possible, documenting everything properly.
I'll leave this open for a while anyway, just in case, you can close it you want.

**Comment by abhinavgupta** [comment]
Thats ok Joaquin. Keep it simple and quick for us to review though.

On Wed, Mar 12, 2014 at 5:56 PM, Joaquín Bermúdez Castanheira <
notifications@github.com> wrote:

> @salil93 https://github.com/salil93 @debugger22https://github.com/debugger22
> @jayrambhia https://github.com/jayrambhia @abhinavguptahttps://github.com/abhinavguptaThis is too much to fit in here, and since right now we're on the GSoC
> inscription period, I understand you're probably too busy to review it.
> If I'd been in your place, I'd probably have torn my hair out with so much
> activity and pull request bombing.
> I'll try to thoroughly review the pros and cons of my proposal and expose
> them as briefly and clearly as possible, documenting everything properly.
> I'll leave this open for a while anyway, just in case, you can close it
> you want.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/BinPy/BinPy/pull/134#issuecomment-37391317
> .

## 

With best regards,
Abhinav Gupta
Research Engineer

_NUS School of Computing_
B.E (Hons.)
_BITS Pilani, K.K Birla Goa Campus_

**Comment by JBeCast** [comment]
Indeed, I should add proper comments and docstrings, thanks for the feedback =).

**Pull request closed without merging**
