### PR TITLE
HalfAdder Modified

### PR DESCRIPTION
**Pull request by salilkapur**
New implementation of HalfAdder without using GATES as the base class. Makes it more flexible and clean.
Added test cases too.

### CODE REVIEW

**Comment by salilkapur** [comment]
@debugger22 @rajat974 Review!

**Comment by debugger22** [comment]
:+1:

**Comment by debugger22** [comment]
We should also change coding style. See https://github.com/BinPy/BinPy/issues/190
I would suggest to use sympy's coding style.

**Comment by debugger22** [comment]
@salil93 I guess it is complete now?

**Comment by debugger22** [comment]
There are assertion errors in the tests

```
ERROR: BinPy.tests.combinational_tests.HalfAdder_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/BinPy/BinPy/BinPy/tests/combinational_tests.py", line 9, in HalfAdder_test
    ha.setInput(0, 1)
AttributeError: HalfAdder instance has no attribute 'setInput'
======================================================================
ERROR: BinPy.tests.combinational_tests.FullAdder_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/BinPy/BinPy/BinPy/tests/combinational_tests.py", line 23, in FullAdder_test
    fa.setInputs(1, 1, 1)
AttributeError: FullAdder instance has no attribute 'setInputs'
```

I wonder why is it showing passed.

**Comment by salilkapur** [comment]
I will sort this out by tonight.

**Comment by salilkapur** [comment]
I have removed Binary Adder, Subtractor and BCDAdder. Will add BCDAdder soon. Please review!

**Comment by debugger22** [comment]
Looks good to me. If you want you can do that in another PR. I wouldn't stall this PR for that.

**Pull request merged**
