### PR TITLE
Removed Migates class

### LINKED ISSUE #225: MIGATES class in gates.py
Is that class really required as the `setinputs` method of the `GATE` class does the same?

### PR DESCRIPTION
**Pull request by akshayah3**
Fixes https://github.com/BinPy/BinPy/issues/225

### CODE REVIEW

**Comment by debugger22** [comment]
```
 class GATES:

      '''
      Base Class implementing all common functions used by Logic Gates
      '''

      def __init__(self, inputs):

          # Clean Connections before updating new connections
          self.history_active = 0  # Ignore history for first computation
          self.outputType = 0  # 1->output goes to a connector class
          self.result = None  # To store the result
          self.outputConnector = None  # Valid only if outputType = 1
```

You'll have to change this `inputs` to `*inputs`.

**Comment by akshayah3** [comment]
Ah! Yes will do.

**Comment by akshayah3** [comment]
Anything else?

**Comment by debugger22** [comment]
Rest is fine.

**Comment by akshayah3** [comment]
There is also redundant code in combinational.py and somehow it is causing the travis to fail.

**Comment by debugger22** [comment]
Yeah things like

```
    def __init__(self, input1, input2, carry):
        GATES.__init__(self, [input1, input2, carry])
```

will also have to be refactored.

**Comment by salilkapur** [comment]
What is the status of this request?

**Comment by ghost** [comment]
Can be closed. Fixed in #247.

**Pull request closed without merging**
