### PR TITLE
Tests Do Not Exit Upon Error - Fix for #239

### PR DESCRIPTION
**Pull request by ragv**
Included a error checking variable to check and persist error if even one test fails while still executing all the commands ....

### CODE REVIEW

**Comment by ghost** [comment]
@debugger pl review

**Comment by debugger22** [comment]
Could you send a commit with multiple failures including style and assertion?

**Comment by debugger22** [comment]
Probably you forgot `git add foo.py`.

**Comment by ghost** [comment]
Works well :) Ill remove those files now ?

**Comment by debugger22** [comment]
Yes!

**Comment by debugger22** [comment]
Thanks!

**Comment by debugger22** [comment]
Please try to put `fixes #239` like things in commit messages and not in PR titles.

**Comment by debugger22** [comment]
Sorry! It's there. :)

**Pull request merged**
