### PR TITLE
Updating the examples and docs. Part 1 / 3

### PR DESCRIPTION
**Pull request by ragv**
Part 1 / 3
- [x] Update the examples / docs for Algorithms
- [x] Create examples for Analog components and Add to docs
- [x] Update examples / docs for new implimentation of connector
- [x] Update docs  for other components of BinPy

In Part 2 / 3 I will add an example project.

In Part 3 / 3 I will finally update the docs one final time.

### CODE REVIEW

**Comment by ghost** [comment]
@debugger22 Pl review ! Algos and ics ill update in subsequent PR's. I'll push the `.rst`s in some time ...

**Comment by ghost** [comment]
I am removing `dev` from docs for now... I'll replace it with `expr` module ...

**Comment by axiom24** [comment]
@rvraghav93 :+1:

**Comment by ghost** [comment]
@sarwarc how do I test sphinx locally ? Once I test it I'll push it ... then pl review one final time before merging !

**Comment by debugger22** [comment]
```
$ make clean
$ make html
```

Then open it in browser and check for correct rendering.

**Comment by ghost** [comment]
@debugger22 Thanks ! :)

**Comment by debugger22** [comment]
These docs do not include rsts of the code.

**Pull request merged**
