### PR TITLE
Added a module to parse logical equations

### PR DESCRIPTION
**Pull request by ragv**
Added a module to parse logical equations and convert it to BinPy compatible Gate level functional statement.

Sample Input:

`print eqnParse('~((((~A)&B&C)^(~A))&E&F&G)')`

Sample Output:

`NAND(G,F,E,XOR(NOT(A),AND(C,B,NOT(A))))`

This can be used along with eval to yield the respective gate object.

### CODE REVIEW

**Comment by ghost** [comment]
@salil93 pl review ! also where do I put this file ? under tools or under Algorithms ?

**Comment by debugger22** [comment]
@rvraghav93 This is awesome!

**Comment by ghost** [comment]
@debugger22 Thanks!! :D

**Comment by ssr09** [comment]
@rvraghav93  Wow! I had the same idea but implemented it a bit late! I would have saved a day if only i could see this in the morning! Anyways, i've implemented a similar thing with a very tiny bit of additional functionality in #111 :)

**Pull request merged**
