### PR TITLE
3.x dependencies added !

### PR DESCRIPTION
**Pull request by rajat974**

### CODE REVIEW

**Comment by jayrambhia** [comment]
@rajat974 this is some neat work. but you need to rebase as there a lot more changes.

**Comment by rajat974** [comment]
@jayrambhia I think the branch is up-to-date

**Comment by jayrambhia** [comment]
I tried merging it. I got conflict. Turns out there are more ICs added in
7400series. Check it out.

**Comment by rajat974** [comment]
Done !

**Comment by rajat974** [comment]
please don't merge for now, i will be adding some more changes.

**Comment by rajat974** [comment]
@jayrambhia we can merge this now!

**Pull request merged**
