### PR TITLE
Refactor Code and PEP8

### PR DESCRIPTION
**Pull request by sai-prasanna**
I am refactoring code incrementally,

The following are changes I made and the reason
1. Changed GATE class to accept tuple *inputs instead of list.It is  better to pass argument to superclass as it is and then convert it into list,this not only complies to DRY principle(no need to do list(inputs)), but is also recommended way of doing handling parameters among class hierarchy in python.
2. Auto PEP8 formatting fixes for the 2 files.PEP8 recommendations makes code standardised and readable

### CODE REVIEW

**Comment by sai-prasanna** [comment]
Can I make more changes to standardise the code.
1. I propose changing all caps class names such as GATES to Gates
2. And also use new style python classes by inheriting object in GATES class.
3. Using Super() for parent **init** call is the better than manually calling parent constructor,this is because things may get muddled when we go for multiple inheritance.I know that we may never go for multiple inheritance in BinPy,but just incase if we make api changes it would be nice to fix this bore-hand.
4. More PEP8 fixes and DRY compliance?????

**Comment by salilkapur** [comment]
Nice work!

You can try to use new style classes. Send us a pull and we can discuss further.

**Comment by salilkapur** [comment]
please rebase and send a pull request again.

**Comment by sai-prasanna** [comment]
Rebased the commit to include MIGATES class

**Comment by sai-prasanna** [comment]
Converted to new style classes by inheriting object.Most part of this commit is pep 8 fixes

**Comment by jayrambhia** [comment]
@sai-prasanna Rebase and make sure it's 3.x compatible. Send another pull request.

**Pull request closed without merging**
