### PR TITLE
Added Truthtable method for ICs

### PR DESCRIPTION
**Pull request by mohitgujarathi14**
'Truthtable' method when applied can give the user a truthtable corresponding to the set of inputs and outputs pins specified by the user for a defined IC.
**Note:** The input( 'i' ) and output( 'o' ) pins list should contain the pin nos. strictly in order of MSB...to...LSB. Also if the IC contains enable pins ,they should be preceding the data-input pins in the input list ( 'i' ).
**Note:** This method doesnt work perfectly for ICs taking in inputs like (0,0,0,1,0,0,0,0),(0,0,0,0,1,0,0,0),(0,0,0,0,0,1,0,0) etc. (eg. Priority Encoder IC 74147, IC74148) 

```
>>>t=IC_4001()
>>>p = {'i':[13,12],'o':[11]}
>>>t.truthtable(p)
   INPUTS      |OUTPUTS
   ------------|-----
     13   12   |  11 
   ------------|-----
      0    0   |   1 
      0    1   |   0 
      1    0   |   0 
      1    1   |   0 
```

PS: This is definitely not a elegant piece of code. So please leave your suggestions down in the comments .

### CODE REVIEW

**Comment by ankitjavalkar** [comment]
Can you elaborate as to why exactly it is that the Truth table method does not work for  IC 74147, IC74148 and similar IC?

**Comment by salilkapur** [comment]
@mohitgujarathi14 Can you try to implement the same feature for other elements/circuits like decoders, mux, gates. They will serve to be more handy.

**Comment by debugger22** [comment]
Can this be merged?

**Comment by debugger22** [comment]
I'm +1 for merging this. @salil93 your views?

**Comment by salilkapur** [comment]
For now we can merge this, but we can enhance this further by making a generic truth table class which can deal with all kinds of circuit elements.

**Comment by debugger22** [comment]
Thanks!

**Pull request merged**
